version: '3.7'

services:
  kafkadrop:
    hostname: kafkadrop
    image: obsidiandynamics/kafdrop:latest
    environment:
      - KAFKA_BROKERCONNECT=kafka:19092
    ports:
      - 9000:9000

networks:
  elastic:
    driver: bridge
